export type Endpoint = { id: string; cat: string; meth: "get"|"post"|"put"|"patch"|"delete"; path: string; search: string; chips: string[]; desc: string; request?: string; response?: string }
export const ENDPOINTS: Endpoint[] = [
  { id: "ep-1", cat: "account", meth: "post", path: "/api/register", search: "register create account throttle verification email", chips: ["public", "throttle:register"], desc: "Creates account (bcrypt), fires verification mail. Responds 201 with user resource — no token until verified flows complete.", request: `{ \"name\": \"Jane Doe\", \"email\": \"jane@example.com\", \"password\": \"••••••••\", \"password_confirmation\": \"••••••••\" }`, response: `{ \"success\": true, \"message\": \"Registered. Verify your email.\", \"data\": { \"id\": 42, \"email\": \"jane@example.com\" } }` },
  { id: "ep-2", cat: "account", meth: "post", path: "/api/login", search: "login authenticate jwt token bearer", chips: ["public", "throttle:login"], desc: "Returns bearer JWT (1h) + refresh capability. Invalid credentials share one generic error to avoid enumeration.", request: `{ \"email\": \"admin@threedos.com\", \"password\": \"password\" }`, response: `{ \"data\": { \"access_token\": \"eyJ0eXAi...\", \"token_type\": \"bearer\", \"expires_in\": 3600 } }` },
  { id: "ep-3", cat: "account", meth: "get", path: "/api/me", search: "me profile current user authenticated", chips: ["auth:api"], desc: "Current user profile incl. roles and verification state. Alias /api/user.", request: ``, response: `` },
  { id: "ep-4", cat: "account", meth: "post", path: "/api/refresh", search: "refresh rotate token jwt", chips: ["auth:api", "throttle:15,1"], desc: "Rotates access token; old token blacklisted on logout only.", request: ``, response: `` },
  { id: "ep-5", cat: "account", meth: "get", path: "/api/email/verify/{id}/{hash}", search: "verify email signed link verification", chips: ["signed"], desc: "Signed verification link → JSON or 302 redirect to frontend verified-success.html. OAuth users must click too — provider flags never auto-trusted.", request: ``, response: `` },
  { id: "ep-6", cat: "catalog", meth: "get", path: "/api/destinations", search: "destinations list browse catalog", chips: ["public", "v1 alias"], desc: "Paginated catalog hub with region/country chain powering continent pills; includes lat/lng for maps.", request: ``, response: `` },
  { id: "ep-7", cat: "catalog", meth: "get", path: "/api/destinations/{destination}/hotels", search: "hotels by destination stays accommodation", chips: ["public"], desc: "Scoped stay listings feeding attach flow and AI enrichment round-robin.", request: ``, response: `` },
  { id: "ep-8", cat: "catalog", meth: "get", path: "/api/flights", search: "flights list air booking boarding pass", chips: ["public"], desc: "Flight inventory — origin/destination/price; detail view renders the boarding pass verbatim from FlightResource fields.", request: ``, response: `` },
  { id: "ep-9", cat: "catalog", meth: "get", path: "/api/weather", search: "weather live meteo temperature wind city", chips: ["public", "throttle:weather"], desc: "Open-Meteo proxy, server-cached; dedicated throttle is abuse-tested in the suite.", request: ``, response: `{ \"temp_c\": 28.4, \"temp_f\": 83.1, \"condition\": \"Clear Sky\", \"wind_kph\": 14.2 }` },
  { id: "ep-10", cat: "trips", meth: "post", path: "/api/trips", search: "create trip planner store itinerary", chips: ["auth \u00b7 verified"], desc: "StoreTripRequest validates → TripService persists root aggregate (+ destinations pivot sync) → TripResource 201.", request: ``, response: `` },
  { id: "ep-11", cat: "trips", meth: "post", path: "/api/trips/{trip}/attach/{type}", search: "attach hotel restaurant attraction flight morph items", chips: ["auth \u00b7 verified"], desc: "Polymorphic attach of hotel|restaurant|attraction|flight into trip_items with ownership policy gate.", request: ``, response: `` },
  { id: "ep-12", cat: "trips", meth: "post", path: "/api/trips/{trip}/fork", search: "fork community clone duplicate lineage", chips: ["auth \u00b7 verified"], desc: "Community forking: clones public trip preserving lineage via parent_trip_id/original_trip_id/is_fork; TripForked mail fired.", request: ``, response: `` },
  { id: "ep-13", cat: "trips", meth: "post", path: "/api/ai/plan", search: "ai generate plan groq llama itinerary days", chips: ["auth \u00b7 verified", "throttle:ai"], desc: "Groq generation: md5 cache (60m) → quota on miss → JSON parse → catalog enrichment binds real hotel/restaurant/attraction IDs + coords. Deterministic fallback guarantees a usable plan.", request: `{ \"city\": \"Cairo\", \"days\": 3, \"travelers\": 2, \"budget\": \"luxury\" }`, response: `{ \"days\": [  { \"day\": 1, \"items\": [    { \"title\": \"Pyramids of Giza\",      \"hotel_id\": 12, \"lat\": 29.97 } ] } ] }` },
  { id: "ep-14", cat: "trips", meth: "post", path: "/api/trips/{trip}/concierge", search: "concierge chat assistant ask ai conversation", chips: ["auth \u00b7 verified", "throttle:ai"], desc: "AI travel assistant Q&amp;A scoped to a trip context; usage metered via AiUsageService.", request: ``, response: `` },
  { id: "ep-15", cat: "commerce", meth: "post", path: "/api/checkout/initiate", search: "checkout initiate pay paymob intention strategy subscription fork package", chips: ["auth \u00b7 verified", "throttle:checkout"], desc: "CheckoutStrategyFactory resolves the purchasable, creates local order, requests Paymob intention, returns hosted-checkout redirect payload.", request: `{ \"strategy\": \"trip_package\", \"package_id\": 7 }`, response: `{ \"data\": { \"order_ref\": \"ORD-8820\", \"redirect_url\": \"https://accept.paymob…\", \"client_secret\": \"…\" } }` },
  { id: "ep-16", cat: "commerce", meth: "post", path: "/api/paymob/webhook", search: "paymob webhook hmac signature callback fulfillment", chips: ["signature-verified", "no auth"], desc: "HMAC SHA-512 verified before any state change; idempotent by merchant_order_id; FulfillOrderListener settles ledger. Prod refuses to boot misconfigured (empty HMAC).", request: ``, response: `` },
  { id: "ep-17", cat: "commerce", meth: "post", path: "/api/me/subscribe", search: "subscribe plans subscription upgrade cancel", chips: ["permission"], desc: "Plan purchase entry (permission:subscribe to plans) — settles via the same webhook fulfillment path.", request: ``, response: `` },
  { id: "ep-18", cat: "system", meth: "get", path: "/api/stats/summary", search: "stats summary dashboard counts public", chips: ["public"], desc: "Aggregate counters powering landing KPIs (destinations, hotels, flights…).", request: ``, response: `` },
  { id: "ep-19", cat: "system", meth: "get", path: "/up", search: "up health check framework probe", chips: ["health"], desc: "Framework health probe used by Railway/Docker monitoring.", request: ``, response: `` },
  { id: "ep-20", cat: "admin", meth: "get", path: "/api/admin/users", search: "admin users list manage rbac", chips: ["permission:manage users"], desc: "Admin directory with activate/block toggles (PATCH /users/{user}/block).", request: ``, response: `` },
  { id: "ep-21", cat: "admin", meth: "post", path: "/api/admin/reports/generate", search: "reports generate pdf xlsx telemetry export queue dompdf", chips: ["role:admin|super_admin"], desc: "Queues GenerateReportJob → branded PDF (DomPDF) / XLSX (OpenSpout) with \"All Time\" default filter; download via GET /admin/reports/{id}/download.", request: ``, response: `` },
  { id: "ep-22", cat: "admin", meth: "delete", path: "/api/admin/categories/{category}", search: "categories delete soft restore crud", chips: ["soft deletes"], desc: "Soft-delete CRUD pattern shared across categories/countries/destinations/flights/hotels with PATCH …/restore counterparts.", request: ``, response: `` },
]

export const GW_NODES = [
  { label: "login", note: "throttle · brute-force" },
  { label: "register", note: "throttle" },
  { label: "refresh", note: "15/min" },
  { label: "ai", note: "quota-guarded" },
  { label: "checkout", note: "money-path" },
  { label: "weather", note: "abuse-tested" },
]